/*
 * Copyright (2023) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.delta.kernel;

import java.util.*;

import io.delta.kernel.client.TableClient;
import io.delta.kernel.data.FilteredColumnarBatch;
import io.delta.kernel.data.Row;
import io.delta.kernel.expressions.Literal;
import io.delta.kernel.types.*;
import io.delta.kernel.utils.CloseableIterator;

import io.delta.kernel.internal.actions.AddFile;
import io.delta.kernel.internal.actions.SingleAction;
import io.delta.kernel.internal.data.GenericRow;
import io.delta.kernel.internal.data.TransactionStateRow;
import io.delta.kernel.internal.util.*;

public interface Transaction {
    /**
     * Get the state of the transaction. The state contains the following:
     * - logical schema
     * - physical schema,
     * - cm mode
     * - table properties (such as generated CDF etc.)
     */
    Row getState(TableClient tableClient);

    /**
     * Get the list of logical names of the partition columns. This helps the connector to
     * do physical partitioning of the data before asking the Kernel to write the data.
     */
    List<String> getPartitionColumns(TableClient tableClient);

    /**
     * Get the expected output of the data that is being written to the table.
     */
    StructType getSchema(TableClient tableClient);

    /**
     * Commit the transaction including the staged data rows generated by either or both
     * `Transaction.stageAppendOnlyData` or `Transaction.stageMergeData`.
     *
     * @param tableClient
     * @param stagedData Iterator of data actions to commit. These data actions are generated
     *                   by the `Transaction.stageAppendOnlyData` or manually created. Manual
     *                   creation of data actions is useful when has the data files and want to
     *                   directly inject them into the table. One important note is that the
     *                   connector should be able to provide the same content if the transaction
     *                   commit fails and needs to be retried.
     * @param previousCommitStatus If the transaction is retried, return the previous status of the
     *                             transaction. This helps the Kernel reuse the conflict resolution
     *                             work done in the previous attempt.
     * @return {@link TransactionCommitStatus} status of the successful transaction. If not
     * successful, returns a state with which the transaction can be retried for commit again.
     * @throws TransactionNonRetryableConflictException when the transaction has encountered a
     * non-retryable conflicts and needs the updates to be regenerated on top of the latest changes
     * in the table.
     */
    TransactionCommitStatus commit(
            TableClient tableClient,
            CloseableIterator<Row> stagedData,
            Optional<TransactionCommitStatus> previousCommitStatus
    ) throws TransactionNonRetryableConflictException;

    ///**
    // * Stage the given `data` as data files in Delta Lake format and generated `Row`s
    // * corresponding to the generated files that will be committed as part of the
    // * `Transaction.commit`.
    // * <p>
    // * The schema of the data is the same as the table logical schema in
    // * ColumnarBatch. Both partition and data columns are part of the batch.
    // * The data could be or could not be grouped together by the partition values.
    // */
    //static CloseableIterator<Row> stageAppendOnlyData(
    //        TableClient tableClient,
    //        Row transactionState,
    //        CloseableIterator<FilteredColumnarBatch> data) {
    //
    //    String columnMappingMode = TransactionStateRow.getColumnMappingMode(transactionState);
    //    StructType physicalSchema;
    //    CloseableIterator<FilteredColumnarBatch> dataToWrite;
    //    switch (columnMappingMode) {
    //        case "none":
    //            dataToWrite = data;
    //            break;
    //        case "name":
    //            physicalSchema =
    //                    TransactionStateRow.getPhysicalSchema(tableClient, transactionState);
    //            dataToWrite = data.map(
    //                    filteredColumnarBatch ->
    //                            new FilteredColumnarBatch(
    //                                    filteredColumnarBatch.getData()
    //                                            .withNewSchema(physicalSchema),
    //                                    filteredColumnarBatch.getSelectionVector())
    //            );
    //            break;
    //        default:
    //            throw new UnsupportedOperationException(
    //                    "Unsupported column mapping mode: " + columnMappingMode);
    //    }
    //    String tableRoot = TransactionStateRow.getTableRoot(transactionState);
    //    long targetFileSize = TransactionStateRow.getTargetFileSize(transactionState);
    //
    //    try {
    //        CloseableIterator<Row> writeResultIter =
    //                tableClient.getParquetHandler().writeParquetFiles(
    //                        tableRoot,
    //                        dataToWrite,
    //                        targetFileSize,
    //                        Transaction.getStatisticsSchema(tableClient, transactionState)
    //                );
    //
    //        // Convert each `FileWriteResult` into a row which represents `AddFile`
    //        return writeResultIter.map(
    //                fileWriteResult -> {
    //                    Map<Integer, Object> valueMap = new HashMap<>();
    //                    valueMap.put(0, fileWriteResult.getString(0)); // path
    //                    // partitionValues
    //                    valueMap.put(1, VectorUtils.stringStringMapValue(Collections.emptyMap()));
    //                    valueMap.put(2, fileWriteResult.getLong(1)); // size
    //                    valueMap.put(3, fileWriteResult.getLong(2)); // modificationTime
    //                    valueMap.put(4, true); // dataChange
    //                    valueMap.put(5, null); // deletionVector
    //                    valueMap.put(6, null); // statistics: TODO: add stats
    //
    //                    Row addFileRow = new GenericRow(AddFile.SCHEMA_WITH_STATS, valueMap);
    //                    return SingleAction.createAddFileSingleAction(addFileRow);
    //                }
    //        );
    //    } catch (IOException ioe) {
    //        throw new UncheckedIOException(ioe);
    //    }
    //}

    /**
     * Given the logical data that needs to be written to the table, convert it into the required
     * physical data depending upon the table Delta protocol options.
     * <p>
     * @param tableClient
     * @param transactionState
     * @param data
     * @return
     */
    static CloseableIterator<FilteredColumnarBatch> transformLogicalData(
            TableClient tableClient,
            Row transactionState,
            CloseableIterator<FilteredColumnarBatch> data) {
        String columnMappingMode = TransactionStateRow.getColumnMappingMode(transactionState);
        // TODO: add support for:
        // - enforcing the constraints
        // - generating the default value columns
        // - generating the generated columns
        switch (columnMappingMode) {
            case ColumnMapping.COLUMN_MAPPING_MODE_NONE:
                return data;
            case ColumnMapping.COLUMN_MAPPING_MODE_NAME: // fall through
            case ColumnMapping.COLUMN_MAPPING_MODE_ID:
                StructType physicalSchema =
                        TransactionStateRow.getPhysicalSchema(tableClient, transactionState);
                return data.map(
                        filteredColumnarBatch ->
                                new FilteredColumnarBatch(
                                        filteredColumnarBatch.getData()
                                                .withNewSchema(physicalSchema),
                                        filteredColumnarBatch.getSelectionVector())
                );
            default:
                throw new UnsupportedOperationException(
                        "Unsupported column mapping mode: " + columnMappingMode);
        }
    }

    /**
     * Stage the given file status as a Delta actions that can be committed in a transaction.
     *
     * @param tableClient
     * @param transactionState
     * @param fileStatusIter Iterator of row objects representing each data file written. The schema
     *                       of the {@link Row} is as follows:
     *                       - file_path: String
     *                       - size: long
     *                       - modificationTime: long
     *                       - stats
     *                         - minValues
     *                           - min values for each column in the statistics required schema
     *                         - manValues
     *                           - max values for each column in the statistics required schema
     *                         - nullCount
     *                           - null counts each column in the statistics required schema
     * @param partitionValues
     * @return
     */
    static CloseableIterator<Row> stageAppendOnlyData(
            TableClient tableClient,
            Row transactionState,
            CloseableIterator<Row> fileStatusIter,
            Map<String, Literal> partitionValues) {
        return fileStatusIter.map(
                fileWriteResult -> {
                    Map<Integer, Object> valueMap = new HashMap<>();
                    valueMap.put(0, fileWriteResult.getString(0)); // path
                    // partitionValues
                    valueMap.put(1, PartitionUtils.serializePartitionMap(partitionValues));
                    valueMap.put(2, fileWriteResult.getLong(1)); // size
                    valueMap.put(3, fileWriteResult.getLong(2)); // modificationTime
                    valueMap.put(4, true); // dataChange
                    valueMap.put(5, null); // deletionVector
                    valueMap.put(6,
                            tableClient.getJsonHandler().serializeAsJson(
                                    fileWriteResult.getStruct(3))); // statistics

                    Row addFileRow = new GenericRow(AddFile.SCHEMA_WITH_STATS, valueMap);
                    return SingleAction.createAddFileSingleAction(addFileRow);
                }
        );
    }

    /**
     * Get the part of the schema of the table that needs the statistics to be collected per file.
     *
     * @param tableClient
     * @param transactionState
     * @return
     */
    static StructType getStatisticsSchema(TableClient tableClient, Row transactionState) {

        long statsColumnIndex = TransactionStateRow.getDataSkippingColIndex(transactionState);
        if (statsColumnIndex <= 0) {
            throw new UnsupportedOperationException(
                    "TODO: we should collect stats for all columns in the schema");
        }
        StructType statsSchema = new StructType();
        StructType physicalSchema =
                TransactionStateRow.getPhysicalSchema(tableClient, transactionState);
        for (int index = 0; index < statsColumnIndex && index < physicalSchema.length(); index++) {
            StructField structField = physicalSchema.at(index);
            DataType dataType = structField.getDataType();
            if (dataType instanceof StructType ||
                    dataType instanceof ArrayType ||
                    dataType instanceof MapType) {
                throw new UnsupportedOperationException(
                        "TODO: support complex type stats collection");
            }

            statsSchema = statsSchema.add(structField);
        }

        return statsSchema;
    }
}
